#!/usr/bin/env bash
# Bash script that configures Nginx
STRING="Hello World!"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "$STRING" > /var/www/html/index.nginx-debian.html
service nginx restart
