#!/usr/bin/env bash
# Bash script that configures Nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx starp
ufw allow 'Nginx HTTP'
echo "Hello World" >  /var/www/html/index.nginx-debian.html
service nginx restart
